package msc.ai.mas.ui.panel;

import jade.core.Agent;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import msc.ai.mas.agent.BookSupplierAgent;
import msc.ai.mas.agent.FrontDeskOperatorAgent;
import msc.ai.mas.agent.LectureAgent;
import msc.ai.mas.agent.LibrarianAgent;
import msc.ai.mas.agent.LibraryAssistantAgent;
import msc.ai.mas.agent.StudentAgent;
import msc.ai.mas.listeners.AgentActionListener;
import msc.ai.mas.ui.AgentUIManager;

/**
 *
 * @author Keshan De Silva
 */
public class AgentWindow extends javax.swing.JFrame
{
    private Agent agent;
    
    public AgentWindow(Agent agent)
    {
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch (Exception ex){}
        initComponents();
        
        this.agent = agent;
        updateUIBasedOnAgent();
        this.setLocation(AgentUIManager.getInitialPosition());
        this.setState(JFrame.ICONIFIED);
    }

    public void showWindow()
    {
        this.setVisible(true);
    }
        
    public void addAgentActionButton(AgentActionListener agentActionListener)
    {
        SwingUtilities.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                JButton button = new JButton(agentActionListener.getActionName());
                button.addActionListener(agentActionListener);
                panelButtons.add(button);
                panelButtons.updateUI();
            }
        });
    }
    
    public void addLog(String logMessage)
    {
        if (this.getState() == JFrame.ICONIFIED)
        {
            this.setState(JFrame.NORMAL);
        }
        
        lblStatus.setText(logMessage);
        txtLog.append(logMessage + "\n");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblAgentIcon = new javax.swing.JLabel();
        lblAgentName = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        panelButtons = new javax.swing.JPanel();

        lblAgentIcon.setBackground(new java.awt.Color(204, 204, 204));
        lblAgentIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/msc/ai/mas/resources/assistant_64.png"))); // NOI18N
        lblAgentIcon.setOpaque(true);

        lblAgentName.setBackground(new java.awt.Color(51, 153, 0));
        lblAgentName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAgentName.setForeground(new java.awt.Color(255, 255, 255));
        lblAgentName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAgentName.setText("Student 1");
        lblAgentName.setOpaque(true);

        lblStatus.setBackground(new java.awt.Color(102, 102, 0));
        lblStatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblStatus.setText("Ready");
        lblStatus.setOpaque(true);

        txtLog.setEditable(false);
        txtLog.setBackground(new java.awt.Color(0, 0, 0));
        txtLog.setColumns(20);
        txtLog.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        txtLog.setForeground(new java.awt.Color(0, 255, 0));
        txtLog.setLineWrap(true);
        jScrollPane1.setViewportView(txtLog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAgentIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAgentName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(panelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAgentIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAgentName, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgentIcon;
    private javax.swing.JLabel lblAgentName;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables

    private void updateUIBasedOnAgent()
    {
        this.setTitle(agent.getLocalName());
        lblAgentName.setText(agent.getLocalName());
        
        String iconName = "student_64.png";
        if (agent instanceof BookSupplierAgent)
        {
            iconName = "supplier_64.png";
        }
        else if (agent instanceof FrontDeskOperatorAgent)
        {
            iconName = "front desk_64.png";
        }
        else if (agent instanceof LectureAgent)
        {
            iconName = "lecture_64.png";
        }
        else if (agent instanceof LibrarianAgent)
        {
            iconName = "librarian_64.png";
        }
        else if (agent instanceof LibraryAssistantAgent)
        {
            iconName = "assistant_64.png";
        }
        else if (agent instanceof StudentAgent)
        {
            iconName = "student_64.png";
        }
        lblAgentIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/msc/ai/mas/resources/" + iconName)));
        
    }
}
