package msc.ai.mas.ui.panel;

import javax.swing.UIManager;
import msc.ai.mas.model.MessageModel;
import msc.ai.mas.ui.tablemodels.MessageLogTableModel;

/**
 *
 * @author Keshan De Silva
 */
public class MessageLogWindow extends javax.swing.JFrame
{
    private static  MessageLogWindow instance;
    private MessageLogTableModel model = new MessageLogTableModel();
    
    private MessageLogWindow()
    {
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch (Exception ex){}
        
        initComponents();
        tableMessageLog.setModel(model);
    }

    public static MessageLogWindow getInstance()
    {
        if (instance == null)
        {
            synchronized (MessageLogWindow.class)
            {
                if (instance == null)
                {
                    instance = new MessageLogWindow();
                }
            }
        }
        
        return instance;
    }
    
    public void addLogMessage(MessageModel messageModel)
    {
        model.addLogMessage(messageModel);
    }
    
    public void showWindow()
    {
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableMessageLog = new javax.swing.JTable();

        setTitle("Message Log");
        setResizable(false);

        tableMessageLog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableMessageLog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMessageLog;
    // End of variables declaration//GEN-END:variables
}
